version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://db:27017/elibrary
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
  db:
    image: mongo
    ports:
      - "27017:27017"
